### ISSUE TITLE
Running `ace add-user` results in TypeError due to issue with encrypted passwords

### ISSUE THREAD

**Issue by krayzpipes** [ace-ecosystem/ACE#33] opened 2019-11-25 05:36 UTC
When adding a user via the ace command line, I receive a TypeError where it appears parser.encrypted_passwords is being iterated; However, it is actually a Nonetype.

This is after a fresh install:

```
ace@ace-2:/opt/ace$ ./ace add-user user1 user1@local.local
Enter password for user1: 
Confirm password for user1: 
Traceback (most recent call last):
  File "./ace", line 3796, in <module>
    args.func(args)
  File "./ace", line 1458, in add_user
    with get_db_connection() as db:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/ace/lib/saq/database/__init__.py", line 327, in get_db_connection
    db = _get_db_connection(*args, **kwargs)
  File "/opt/ace/lib/saq/database/__init__.py", line 271, in _get_db_connection
    'db': _section['database'],
  File "/usr/lib/python3.6/configparser.py", line 1234, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/lib/python3.6/configparser.py", line 800, in get
    d)
  File "/opt/ace/lib/saq/configuration.py", line 38, in before_get
    if key in parser.encrypted_passwords:
TypeError: argument of type 'NoneType' is not iterable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 543, in add_proc_info
    self.add_proc_environ(pid, extraenv)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 610, in add_proc_environ
    env = _read_file('environ', dir_fd=proc_pid_fd).replace('\n', '\\n')
  File "/usr/lib/python3/dist-packages/apport/report.py", line 73, in _read_file
    with open(path, 'rb', opener=lambda path, mode: os.open(path, mode, dir_fd=dir_fd)) as fd:
  File "/usr/lib/python3/dist-packages/apport/report.py", line 73, in <lambda>
    with open(path, 'rb', opener=lambda path, mode: os.open(path, mode, dir_fd=dir_fd)) as fd:
TypeError: argument should be integer or None, not list

Original exception was:
Traceback (most recent call last):
  File "./ace", line 3796, in <module>
    args.func(args)
  File "./ace", line 1458, in add_user
    with get_db_connection() as db:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/ace/lib/saq/database/__init__.py", line 327, in get_db_connection
    db = _get_db_connection(*args, **kwargs)
  File "/opt/ace/lib/saq/database/__init__.py", line 271, in _get_db_connection
    'db': _section['database'],
  File "/usr/lib/python3.6/configparser.py", line 1234, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/lib/python3.6/configparser.py", line 800, in get
    d)
  File "/opt/ace/lib/saq/configuration.py", line 38, in before_get
    if key in parser.encrypted_passwords:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by krayzpipes** [comment] 2019-11-25 05:39
Looks like this may have been introduced during the integration feature implementation.

**Comment by krayzpipes** [comment] 2019-11-25 06:05
The `load_encrypted_passwords` method of the ExtendedConfigParser class was called when the ace program is run. And within `load_encrypted_passwords`, the method `get_encrypted_passwords` is called.

```python
# in $SAQ_HOME/ace

# NOTE we call this function if the user provides a password or not
saq.CONFIG.load_encrypted_passwords()
```

```python
# in lib/saq/configuration.py

class ExtendedConfigParser(ConfigParser):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # dict of encrypted passwords where key = section_name.option_name, value = decrypted password or None
        self.encrypted_passwords = None
        self.initializing = True

    def load_encrypted_passwords(self):
        self.encrypted_passwords = get_encrypted_passwords()
        self.initializing = False
```

Then...

```python
# in lib/saq/configuration.py

def get_encrypted_passwords():
    """Returns a dict with key = section.key and value = either the decrypted password or None if decryption is not enabled."""
    if not os.path.exists(encrypted_password_db_path()):
        return None
```
**Note the `return None`

and it's returning none because this config section doesn't exist (`encrypted_password_db_path`):

```python
# in lib/saq/configuration.py

def encrypted_password_db_path():
    """Returns the full path to the sqlite database that contains the encrypted passwords."""
    return os.path.join(saq.DATA_DIR, saq.CONFIG['global']['encrypted_password_db_path'])
```

So far, I haven't found a place where the 'encrypted_password_db_path' is stored to disk anywhere.

@unixfreak0037  --> since I don't fully understand this new section of code (encrypted password portion), maybe you can take a look? If not, I will try to figure it out when I can get to it.

**Comment by krayzpipes** [comment] 2019-11-25 06:43
Here's the original `EncryptedPasswordInterpolation` class:

```python
class EncryptedPasswordInterpolation(Interpolation):
    def before_get(self, parser, section, option, value, defaults):
        # if we haven't set this attribute yet then just return the value as-is
        # this is will the case when we're initializing
        if parser.encrypted_passwords is None and parser.initializing:
            return value

        key = f'{section}.{option}'
        # if we're asking for an encrypted password and we've decrypted it, return that value
        if key in parser.encrypted_passwords:
            if parser.encrypted_passwords[key] is None:
                # if we haven't decrypted it and we're asking for it, raise an error
                raise RuntimeError(f"configuration section {section} option {option} has encrypted password but no decrypt key was used\n"
                                    "maybe you missed using the -p option for the ace command")
            else:
                return parser.encrypted_passwords[key]
        else:
            # otherwise return the value as-is
            return value
```

Do you want this to raise an error or return the value it was given?  Example fix/mitigations might be to add a default encryption sqlite path to the default config, raise an error, or return the original value.

My assumption is that we would like to return an error as there should be a default path to an encryption DB? If not, do we return the value that was given? Example fix:

```python
class EncryptedPasswordInterpolation(Interpolation):
    def before_get(self, parser, section, option, value, defaults):
        # if we haven't set this attribute yet then just return the value as-is
        # this is will the case when we're initializing
        if parser.encrypted_passwords is None and parser.initializing:
            return value
        
        # If None instead of a dict of encrypted passwords, and parser.initializing is False, then we were
        # unable to find the encryption sqlite database.
        if parser.encrypted_passwords is None:
            raise RuntimeError(f"There was an issue locating the encryption storage location")

        key = f'{section}.{option}'
        
        # if we're asking for an encrypted password and we've decrypted it, return that value
        if key in parser.encrypted_passwords:
            if parser.encrypted_passwords[key] is None:
                # if we haven't decrypted it and we're asking for it, raise an error
                raise RuntimeError(f"configuration section {section} option {option} has encrypted password but no decrypt key was used\n"
                                    "maybe you missed using the -p option for the ace command")
            else:
                return parser.encrypted_passwords[key]
        else:
            # otherwise return the value as-is
            return value
```

**Comment by unixfreak0037** [comment] 2019-12-16 03:57
I believe this has been fixed in the lastest set of commits. Cannot reproduce the error any more.

**Closed by unixfreak0037** 2019-12-16 03:57 UTC
Labels: bug
